theme: jekyll-theme-cayman
title: Moosic - A simple Discord music bot
image: https://cdn.discordapp.com/avatars/444633099712856064/4aa91b67acc0eff7b422b42a4d1d3e48.png?size=1024
url: https://moosic.advaith.fun
